### ISSUE TITLE
request-validator usage is wrong

### ISSUE THREAD

**Issue by bugventure** [Muscula/json-schema-benchmark#2]
To have `request-validator` run the actual validation, you need to call `validate(value)` on the object returned after creating the validator with a particular schema.

[Link to source](https://github.com/Muscula/json-schema-benchmark/blob/master/index.js#L109)

This line should really be `instance.validate(json)`.

**Comment by Muscula** [comment]
Sorry about that. I've fixed it. 
Thank you so much for pointing it ous
