### ISSUE TITLE
Opitonal JSON-schema tests should be criteria for inclusion of a validator into the performance tests

### ISSUE THREAD

**Issue by bugventure** [Muscula/json-schema-benchmark#3]
Your criteria for including a validator into the performance tests shouldn't really take optional tests into account. All the tested validators are run either on node or in the browser. The JavaScript runtimes there cannot handle JSON parsing in a way that is compatible with the [bignum](https://github.com/json-schema/JSON-Schema-Test-Suite/blob/develop/tests/draft4/optional/bignum.json) and [zeroTerminatedFloats](https://github.com/json-schema/JSON-Schema-Test-Suite/blob/develop/tests/draft4/optional/zeroTerminatedFloats.json) test cases. As for the [format](https://github.com/json-schema/JSON-Schema-Test-Suite/blob/develop/tests/draft4/optional/format.json) tests, the [JSON-schema spec](http://json-schema.org/latest/json-schema-validation.html#anchor106) clearly states that conforming validators __MAY__ choose to support the `format` keyword, but are not required to.

**Comment by Muscula** [comment]
You are absolutely right. I had this on the radar, now it's implemented. `request-validator` now qualified for the benchmark.
