### ISSUE TITLE
clarify JSCK error report

### ISSUE THREAD

**Issue by gilesbowkett** [Muscula/json-schema-benchmark#5]
[this doc](https://github.com/Muscula/json-schema-benchmark/blob/master/reports/jsck.md) shows JSCK failing some official JSON Schema tests.

[this code](https://github.com/pandastrike/jsck/blob/master/test/draft4/official.coffee) explicitly articulates that we don't support those features, as do [the JSCK README](https://github.com/pandastrike/jsck#coverage) and [this comment](https://github.com/Muscula/json-schema-benchmark/issues/4#issuecomment-72278511).

it would be nice to put this info in the doc, since "failing a test" doesn't usually imply "deliberately elected not to support a feature."

**Comment by Prestaul** [comment]
It might be nice to differentiate between required test failures and the optional feature tests as well. 

Honestly, the optional/zeroTerminatedFloats tests are not relevant to javascript implementations of json-schema at all, they are intended for languages that differentiate between `1.0` and `1`.  Given [the wording of the spec](http://json-schema.org/latest/json-schema-core.html#anchor19) you could even argue that the tests are not valid in any implementation as `1.0` is a "mathematical integer".

> ...for interoperability reasons, JSON values used in the context of JSON Schema, whether that JSON be a JSON Schema or an instance, SHOULD ensure that mathematical integers be represented as integers as defined by this specification.
